---
title: "Publications"
---

See also:

-   [OCRID iDs](http://orcid.org/0009-0004-7681-514X)

## MSc. Thesis/Project

-   Title: Joint modeling of functional ability measures and competing risk for stroke patients. Jornal: [Bahir Dar University](www.bdu.edu.et) [Link](http://ir.bdu.edu.et/handle/123456789/14036)

[**Supervisors**]{.underline}**:**

1.  Name: Dr Zelalem G, Dessie

    Email: zelalem_getahune\@yahoo.com

    Address: University of KwaZulu Natal, South Africa

2.  Name: Dr Lijalem Melie Tesfaw

    Email: lijalemmelie\@gmail.com

    Address: university of Queensland, Australia

## Publications

-   Title: Exploring functional abilities and competing risks among stroke patients: a longitudinal and survival analysis study at Felege Hiwot Referral Hospital, Ethiopia. 2024. 14(5): p. e073384. Jornal: **BMJ Open.** [doi](doi:10.1136/bmjopen-2023-073384)

-   Title: Spatial variation of short birth intervals and their determinant factors among reproductive women in Ethiopia using a geographically weighted regression model. 2024. 11: p. 1363844. Jornal: **Frontier in Medicine** [doi](doi:10.3389/fmed.2024.1363844)

## Under Review

-   Title: Competing Risks analysis in a case of stroke patients at felege hiwot referral hospital, Bahir Dar Ethiopia. Frontier in stroke. 2024. 10:1442989 Journal: **Frontier in Stroke** [link](https://review.frontiersin.org/review/bootstrap/3871bec4-0494-4e23-abbe-04ec6e05772e)
-   Title. Modelling spatial distribution and determinants of home delivery in Ethiopia: geographically weighted regression. Journal: **Scientific report**
-   Title. Identifying factors that determine functional status of stroke patients using partial proportional odds model at Felege Hiwot referral hospital Ethiopia. 2024.\
    Journal: **Scientific report** [link](https://submission.springernature.com/submission/1d47242b-8d45-444f-b013-354d34371436)
-   Title. Maru Z, Haymanot B, Awoke S,.2023. Determinants of blood sugar level and time to first remission for type 1 diabetic patients under treatment; Comparison of separate and joint models. Jornal: **Hematology and Oncology**
-   Title. Trend and Forecast of Measles Disease, In East Gojjam Zone, Amhara Region, Northwest Ethiopia. Journal: **Health, Population and Nutrition**

## Under preparations

-   Title: Understanding Trends and Determinants of Healthcare Utilization for Common Childhood Illnesses in Ethiopia

-   Title: Exploring frailty and factor identification in women who had breast cancer at Felege Hiwot referral hospital, Ethiopia

-   Title: Joint modelling of CD4 cell count change and adherence to HAART at Injibara general hospital, Ethiopia

-   Title: Determinant factor of longitudinal pulse pressure among hypertensive patients treated Assosa general hospital, Ethiopia

-   Title: Major risk factors on time to recovery and competing lost follow up among diabetic patients at Felege Hiwot referral hospital, Ethiopia
