---
title: "About Me"
---

-   Currently, I am doing my Second master's in Computational Health Informatics (Bionformatics) at University of Cape Town, South Africa. I have another master's degrees in statistics (Biostatistics) from Bahir Dar University and and BSc degree in Statistics at Debre Markos University, Ethiopia. coupled with 7+ years of experience in project leading, data management, analysis, and lecturing. These experiences equipped me with a deep understanding of complex data, its management, analysis and use with application of different statistical methods. I have interest in bioinformatics, biostatistics, epigenetics, genomics, and biomedical research. I have a strong proficiency in (R/RStudio, Python, Linux/Bash, Git, High-Performance Computing (HPC) environments, and a wide range of bioinformatics tools.).

## Education

-  **University of Cape Town, South Africa\| Cape Town, South Africa**

    -  MSc in Computational Health Informatics (Bioinformatics)
    
        \| February 2025 - Present   

-   **Bahir Dar University, Ethiopia\| Bahir Dar, Ethiopia**

    -   MSc in Biostatistics

        \| Sptember 2020 - August 2022

-   **Debre Markos University, Ethiopia\| Debre Markos, Ethiopia**

    -   BSc in Statistics

        \| September 2014 - July 2017
        
-   **Assosa University, Ethiopia\| Assosa, Ethiopia**

    - Higher Diploma Programme(HDP)
      
        \| September 2018 – February 2020

-   **Africa Leadership Group(ALX)**

    -   Vertiual Assistant and Data Analyst

        \| July - Agust 2022

## Experience
-   **Intern Bioinformatics** at: [International Centre for Genetic Engineering and Biotechnology(ICGEB)](https://www.icgeb.org/)

    \| 2025-09-15 -to- 2025-10-30.

-   **Lecturer** at: [Assosa University](http://www.asu.edu.et/)

    \| 2017-10-23 -to - 2024-11-15.

-   **Biostatistician** at: Loza Statistical consultancy and training Service Plc

    \| 2022-05-01 - to - 2024-04-30

-   **Data Manager** Remotely at: Jeju Research and statistical consultancy plc

    \|2024-05-05 - to - 2024-12-31.
    
- **Monitoring AND Evaluation** Remotely at: Shebel Berenta Agricultural office – Yeduha, Ethiopia 

    \|2018-10-22 – to - 2024-08-16 
